### ISSUE TITLE
When populate again only image repopulate

### ISSUE THREAD

**Issue by lajlev** [preciousforever/sketch-data-populator#10]
![bug-sketch-data-populator](https://cloud.githubusercontent.com/assets/133836/8251553/d0a369fc-167d-11e5-8439-b17f05df4af4.gif)

If I press `cmd + z ` and the press populate again it works.

**Comment by nitrada** [comment]
@lajlev that's because once populated, the text {placeholders} lose their meaning. the image layers names remain the same though.

**Comment by nitrada** [comment]
@lajlev I think we have an idea how to fix this (need to persist the original string with {placeholders} before populating a text layer). working on it.

**Comment by lajlev** [comment]
:+1: Awesome. Looking forward to it.

**Comment by nitrada** [comment]
it's now possible to re-populate text layers:
https://github.com/preciousforever/sketch-data-populator/commit/db3d45cdb900f33d5d340dd115495466b6702542
