### ISSUE TITLE
Inserted symbols not populating with data

### ISSUE THREAD

**Issue by meganfrankosky** [preciousforever/sketch-data-populator#102]
Hello! First off, I absolutely love what you have done, this is a very useful plugin! One issue I am having is with populating data into inserted symbols. I have tried several times with the demo file to populate data into an inserted symbol but this does not seem to be working. When I insert the symbol, select the symbol, then select the data to be loaded, the symbol remains the same (or with grid -  it recreates the original symbol given the grid parameters). I have also tried this with my own JSON file - the normal placeholders (not inserted symbols) work brilliantly, but inserted symbols do not populate. Am I missing something, or is this a bug?

**Comment by nitrada** [comment]
Hey @meganfrankosky, which version of Sketch and Data Populator do you use? And what do you mean with "inserted symbol"?

**Comment by meganfrankosky** [comment]
I have Sketch version 44.1 and Data Populator 2.1.3. 

By inserted symbol, I mean a group of objects with multiple {placeholders} that have been converted to a symbol, then inserted as a symbol onto the art board. Does that make sense?

**Comment by sixtyfourthirtytwo** [comment]
I've got the same issues, running the same versions of Sketch and SDP.

**Comment by nitrada** [comment]
@meganfrankosky @sixtyfourthirtytwo please update the plugin to v2.2.0 and let us know if it works

**Comment by sixtyfourthirtytwo** [comment]
@nitrada Seems to be working now. Thank You!

**Comment by meganfrankosky** [comment]
@nitrada working for me now as well, thanks very much!!

**Comment by nitrada** [comment]
great, you're welcome :)
