### ISSUE TITLE
placeholders text within sentence

### ISSUE THREAD

**Issue by alirenttrack** [preciousforever/sketch-data-populator#105]
Would love to have placeholders within text areas.

This almost does the job: 
{name,price,date,time|& · } adding in a '·' 

so it could be: 
{name,price,|& hello there } which gives me name hello there price hello there.

However, what if we could do:
For only {price} you could be surfing too. Please signup by {date} to register.

I'm working around with stock data in cells at the minute (such as 'you could be surfing too. Please signup by ' would be a cell). Any thoughts?

Amazing work guys.

**Comment by chrleon** [comment]
For only {price} you could be surfing too. Please signup by {date} to register.

This works for me
