### ISSUE TITLE
arbitrary string concatenation not working 

### ISSUE THREAD

**Issue by alirenttrack** [preciousforever/sketch-data-populator#106]
Arbitrary string concatenation such as {propertyname}, {creditfee} does not work. See Gif.

![concatenation](https://user-images.githubusercontent.com/26285333/30036073-9065af2e-9175-11e7-999b-906969bcd6f1.gif)

**Comment by tjdaveyuk** [comment]
Same for me, any update in this??

**Comment by tjdaveyuk** [comment]
@alirenttrack the curly braces should go around the whole thing. ie. {propertyname, creditfee}
