### ISSUE TITLE
AWS image URLs need to be https

### ISSUE THREAD

**Issue by rynhsy** [preciousforever/sketch-data-populator#111]
I just had an issue (mainly from my team's CMS build) some of the images on AWS were referenced with just http in the URL instead of https 

The http images were not retrieved by the plugin, but they do show in the browser without the "s" at the end.

I did a find and replace on a local copy of the JSON file to change them all to https, but would be good if it could still retrieve the image.

Love the plugin. Keep up the good work!

**Comment by nitrada** [comment]
@rynhsy AFAIK, this is required by Sketch to work.
