### ISSUE TITLE
Doesn't work with symbols in Sketch 47

### ISSUE THREAD

**Issue by andyra** [preciousforever/sketch-data-populator#118]
Data Populator doesn't work on symbols or nested symbols with the latest version of Sketch. It works fine with the previous version (46).

**Comment by chiliberto** [comment]
It looks like this is related to broken image placeholders. https://github.com/preciousforever/sketch-data-populator/issues/119

I found that the text placeholders will work as long as there are no image placeholders. This is unfortunate because in Sketch 47 they finally introduced libraries.

**Comment by lpredster** [comment]
Yeah, it seems ok with text, just not images.

**Comment by nitrada** [comment]
does v2.2.1 work for you all?

**Comment by andyra** [comment]
Bingo, it sure does! Thanks so much!
