### ISSUE TITLE
Image placeholders are broken with Sketch 47

### ISSUE THREAD

**Issue by chiliberto** [preciousforever/sketch-data-populator#119]
![populator_sketch47](https://user-images.githubusercontent.com/1380294/31469227-e2b5c132-ae95-11e7-89aa-f7b1a5d349f1.gif)

Image placeholders aren't getting updated or replaced with images at all. 

Plus they are causing other placeholders to break. 

I tested this with one of your demo presets.

**Comment by alirenttrack** [comment]
Having to keep two versions of Sketch on my machine to manage this. Would love a fix here.

**Comment by johndilworth** [comment]
Looks like image placeholders are not getting updated due to this method that has been deprecated in Sketch 47
```return MSImageData.alloc().initWithImage_convertColorSpace(image, false);```

Replacing it with the following seems to fix the issue
```return MSImageData.alloc().initWithImage(image)```

**Comment by paulwan** [comment]
@johndilworth It works!  Thank You!

**Comment by rhawbert** [comment]
@paulwan How can I fix it myself in my local installation? 
Editing _src/library/data.js_ doesn't seem to fix it.

**Comment by paulwan** [comment]
@rhawbert what‘s your sketch version? I was change the code by johndilworth's method (sketch v47.1), it works.

**Comment by rhawbert** [comment]
@paulwan latest (v47.1)... I've also tried to edit the line 4935 on "...Plugin-folder/Sketch Data Populator.sketchplugin/Contents/Sketch/plugin.js" but it is still throwing the error _"Some images could not be loaded. Please check the URLs"_

**Comment by rhawbert** [comment]
Problem sorted, just wanted to share it here... my colleague found out that **nsurl** only accepts secure (https) URLs.

**Comment by lpredster** [comment]
@johndilworth Thanks!! This fixed the image issue. However, Nested symbols are still not getting populated with the correct JSON values, all are just getting populated with the first item. I even tried the demo file and it's not working

Is this an issue for others?

**Comment by adryweber** [comment]
@johndilworth Yes, thank you! It really works.

**Comment by Oli4k** [comment]
In the sketch document I'm working on Data Populator stopped working at all if there's any image in the group I'm trying to populate. My URLs are https.

**Comment by nitrada** [comment]
does v2.2.1 work for you all?

**Comment by prabhasp** [comment]
v2.2.1 worked for me, but getting it required an uninstall / reinstall. The "update plugins" process didn't update to v2.2.1. In case this helps someone.

**Comment by steamfrog2007** [comment]
Help me out please, where do I get v 2.2.1 and where do I find the files to change as listed above Im not sure what file to look at.

Thanks

**Comment by andyra** [comment]
I'm using 2.2.1 and symbol overrides aren't working if an image is included in the symbol (if there's no image in the symbol, overrides work as expected). I tried swapping out these bits to no effect:
```javascript
// Replaced this deprecated method to no effect
// return MSImageData.alloc().initWithImage_convertColorSpace(image, false);

return MSImageData.alloc().initWithImage(image);
```

**Comment by evandeininger** [comment]
@johndilworth This worked! Thank you. If I get free time I'll see about making a PR unless you'd like to do the honors ;)

I'm having the same issue as lpredster though, nested symbols only get updated when I rerun data populator over them. At least I can still do that but what a pain.

@andyra That fix worked for me with sketch 48.1 could you be using an old version of sketch?

**Comment by andyra** [comment]
@evandeininger Yes, I'm using Sketch 48.1. To be clear, here's what I'm experiencing both before and after the suggested fix above:

- **Library symbol with image**: no overrides update
- **Detached library symbol with image**: text overrides update, image overrides don't
- **Library symbol, no image**: works as expected

**Comment by nitrada** [comment]
hey, something’s broken in 48 and we’ll ty to fix it soon. it seems it’s again a general issue with image placeholders, not just symbol overrides. 

thanks for using the plugin and providing your feedback!

**Comment by nitrada** [comment]
this should fix the issues with 48:
https://github.com/preciousforever/sketch-data-populator/releases/tag/v2.2.2

**Comment by andyra** [comment]
@nitrada, everything is working as expected with the latest update. Thanks!
By the by: this is the most useful plugin I use and I can't imagine working without it. Keep up the good work!

**Comment by nitrada** [comment]
@andyra great to hear this! :)

btw, from v2.2.2 on, the internal sketch update mechanism will work for data populator.

**Comment by nitrada** [comment]
hey all, please check out v2.3.1 – we optimized the way you manage your preset library and the plugin bundle now doesn't contain any images anymore, making internal updates much faster.

would be great to hear if it works well for you!
https://github.com/preciousforever/sketch-data-populator/releases/tag/v2.3.1
