### ISSUE TITLE
Feature Request: `capitalize` filter

### ISSUE THREAD

**Issue by nwpappas** [preciousforever/sketch-data-populator#121]
Feature request for a 'capitalize' filter, which would behave as `text-transform: capitalize` style does.

Input:
```
{
  name: {
    first: 'sally',
    last: 'ferguson'
  }
}
```

Filter:
```
{name.first | capitalize} {name.last | capitalize}
```

Output:
```
Sally Ferguson
```

**Comment by nitrada** [comment]
@nwpappas check this out:
https://github.com/preciousforever/sketch-data-populator/pull/126

**Comment by nitrada** [comment]
yeah, we’ll release a new version soon. thanks again!

**Comment by nitrada** [comment]
introduced with [v2.3.2](https://github.com/preciousforever/sketch-data-populator/releases/tag/v2.3.2)
