### ISSUE TITLE
Crashes Sketch

### ISSUE THREAD

**Issue by rgbk** [preciousforever/sketch-data-populator#125]
Since a while now hitting Apple Shift X crashes Sketch, every-time. I'm on the latest Sketch, and have enjoyed using your plugin on a project I'm working on for a year now. I can't share the file, but can share the crash report if that helps. I can't find any other plugins that shares the same shortcut in my config.

**Comment by nitrada** [comment]
can you try closing sketch and re-opening it and then test populating a simple object in a simple file?

**Comment by nitrada** [comment]
@rgbk habe not been able to reproduce. if it still occurs to you, please reopen this issue.
