### ISSUE TITLE
handling empty fields (no data)

### ISSUE THREAD

**Issue by nitrada** [preciousforever/sketch-data-populator#13]
Currently, if a {placeholder} doesn't get data from populating, it says "undefined".

Would be great if his could be configured – a string (or strings) that could be used instead of "undefined" (not sure how and which granularity).

But also, imagine having {price} and {oldprice}. Some data rows don't have "oldprice" though because there's no price change to communicate. In this case it would be good if a placeholder could be omitted.

I'm not all clear how we could do this. Flag a {placeholder} as optional somehow?

**Comment by lukas77me** [comment]
I think a reasonable solution could be to omit the placeholder if there is no value to populate it with unless a specific custom string is specified some syntax. 

For example, {oldprice} could mean that if no value is present in the data, it would be omitted (replaced with empty string) but {oldprice ? n/a} would populate the placeholder with 'n/a' instead (string after the ?).

I'm not sure about the '?' syntax but I think it'd be a great way to easily configure what happens to each placeholder with full control.

**Comment by nitrada** [comment]
@lukas77me I think that's a great idea! It should still be possible to set a "default string" (to get rid of "undefined") somewhere (manifest?)

@rockitbaby what do you think about the syntax? any recommendation beyond the "?"?

**Comment by nitrada** [comment]
also, if a image/icon field ist empty, why not turn off the fill? this way, it would be possible to place a bg behind the actual asset placeholder that becomes visible once there's no actual data.

when re-populating, fille image/icon fields should turn the fill on again.

example: https://www.dropbox.com/s/yzjcbvdy7mvs8b3/image-placeholders.sketch.zip?dl=0

**Comment by nitrada** [comment]
our heavy usage of the plugin has shown that we always need to try to keep our {placeholders} as short as possible. For example, {first_name} {last_name} is too long – if you populate it with hundreds of names, the placeholders will still most often be longer than the actual data. We'd rather go for {firstname} {lastname} or even {firstn} {lastn}.

So adding "? No First Name", leading to {firstn ? No First Name} can be quite counterproductive in that regard.

On the other hand, if we have something like a global "no data" string configured, which could be used in 80% of the cases, it should be ok. So the behavior could be:

{placeholder} = no data = omit (= empty string)
{placeholder ?} = global "no data" string
{placeholder ? No data available} = no data = No data available

Regarding the syntax: as short as possible, but also meaningful would be best. I was thinking about something like this – not sure if it makes sense though

{placeholder!No data available}

Means:
- no spaces
- ! instead of ?

Does this make sense @lukas77me @rockitbaby?

**Comment by rockitbaby** [comment]
The default behavior without any configuration should be an empty string.
"By default a variable "miss" returns an empty string." as in https://mustache.github.io/mustache.5.html

Regarding the Inline Defaults:

`{placeholder ? No data available} `
is missleading as it looks similar to javascript's conditional shorthand.

`{placeholder!No data available}`
also not that meaningful and confusing with the meaning of `!` in programing languages.

I propose one of the following syntax variants:
`{company_name or 'self-employed' }`
`{company_name || 'self-employed' }`

---

> global "no data" string configured

a better name for this configuration could be "global defaults".
Do you really need a global configuration? And what does 'global' mean? Is this configuration per sketch file / per artboard / per page? Could become confusing, if you do not exactly know / see where a string that appears in your artboard is coming from.

As first implementation step I would start with Inline Defaults.

**Comment by lukas77me** [comment]
Personally I would go for the ```{company_name || self-employed}``` as @rockitbaby suggested but without the ```' '``` around the string since you could have ```'``` in the string itself and then we'd need to escape it, etc. I suppose it's very unlikely that you'd have ```||``` in the string. What you do think?

**Comment by nitrada** [comment]
@lukas77me could also be
`{company_name || self-employed}` (no spaces)?

**Comment by nitrada** [comment]
now possible since https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.1.0
