### ISSUE TITLE
'Populate again' switches to another page

### ISSUE THREAD

**Issue by tdemooij** [preciousforever/sketch-data-populator#14]
When I use 'Populate Again' in a document with multiple pages, the view switches to the last page. It should just stay on the current page. See the behaviour in this [screencast](https://www.dropbox.com/sc/utthr4hjw6b7ytc/AABBWWHebkjGGR32pOJng1gra).

**Comment by lukas77me** [comment]
This issue should be now be fixed in the 'development' branch. Please check it out.

**Comment by tdemooij** [comment]
Works great now, thanks!
