### ISSUE TITLE
Multiple text styles get overridden on replace

### ISSUE THREAD

**Issue by rorysmyth** [preciousforever/sketch-data-populator#15]
screenshot

![image](https://cloud.githubusercontent.com/assets/1512382/8677520/7ba49204-2a47-11e5-9205-fd98a998fa30.png)

^ message if a different font weight from name

**Comment by nitrada** [comment]
@rorysmyth yeah, that's the case unfortunately and we haven't found a way around it. I fear it has to do with a limitation on the Sketch side and we cannot really solve it for the plugin.

Any comment on this from @lukas77me or @bomberstudios?

**Comment by lukas77me** [comment]
So far, I haven't found any way to extract the font/text style from a substring inside a text layer. It'd be great if @bomberstudios could point us in the right direction.

**Comment by nitrada** [comment]
@lukas77me maybe this could hint to a solution? https://medium.com/sketch-app-sources/sketch-plugin-snippets-for-plugin-developers-e9e1d2ab6827 (scroll down to "Working with Text Layers")?

**Comment by lukas77me** [comment]
The article points out a great way to set the style to a range so I'll see if I can get it to detect the initial style ranges too. Then it'll be possible to reapply the original style.

**Comment by knowsnotmuch** [comment]
Came to log this request as well - glad to see its already being deliberated. Thanks for the wonderful plugin anyway!

**Comment by dantz** [comment]
I'm new to the data populator and I tripped over this problem as well. Thanks for working on it.
