### ISSUE TITLE
Broken copy&paste 

### ISSUE THREAD

**Issue by mvdandrieux** [preciousforever/sketch-data-populator#16]
Fantastic app ! Just a note: The plugin seems to remember the blocks where a json variable was input and replaced. This prevents copying of any text block which contained a variable at some point of his history, even if you fill it up with a new variable. Lots of unatural manipulation needed to handle these blocks.

**Comment by nitrada** [comment]
Yes, the plugin persists the original string with its {placeholders} in the text layer. We do this to be able to populate again without the need to manually set new placeholders. Like that, you can for example shuffle through dozens of data. 

To get rid of it, use the "Restore Placeholders" command. This will remove it from the text layer and write back the original string into the layer. From here, you can use the layer as a regular text layer again – or go on and populate it again. 

Does this work for you, @mvdandrieux?

**Comment by mvdandrieux** [comment]
@nitrada YES. Fantastic new feature. Just downloaded the last build and it worked seamlessly. Thank you for the great piece of loveware.
