### ISSUE TITLE
Multiple Array ID's in JSON not working

### ISSUE THREAD

**Issue by Booozz** [preciousforever/sketch-data-populator#17]
Hey,
i'm trying out Sketch Data Populator, and struggled with the integration of different data sets inside the JSON file. It might be that i am doing sth wrong, so maybe you guys can help me. I attached the key screenshots from my setup:

![json](https://cloud.githubusercontent.com/assets/13080099/8719702/ee040264-2bad-11e5-8185-8f7c8bd1565d.png)
![layer](https://cloud.githubusercontent.com/assets/13080099/8719707/f7795876-2bad-11e5-8164-2816749b690b.png)
![artboard](https://cloud.githubusercontent.com/assets/13080099/8719714/072bbfe8-2bae-11e5-84fb-e153aa6a9aef.png)

Thanks in advance, any hint is appreciated!

**Comment by maxfell** [comment]
Did you try selecting all `partner.title` elements instead of just one?

**Comment by nitrada** [comment]
@Booozz this should work! Like @maxfell said, select all elements and run the command. Let us know if this doesn't work.

**Comment by Booozz** [comment]
Thank you guys, this is working. I selected before global layergroups like "site", "content" or the whole artboard itself only and then the plugin inserted just one data set. Now is cool! <2
