### ISSUE TITLE
Error with commas in margins

### ISSUE THREAD

**Issue by dinko** [preciousforever/sketch-data-populator#21]
This plugin is awesome, for starters. ;)

I'm on a Mac with German localization and therefore, the decimal separator is a comma and not a point. The grid options in certain situations come up with `0,0` by default, which causes an error if not corrected to `0` or `0.0` manually.

Maybe you can do some sort of parsing on the input, that would be great!

By the way…Sketch has the same problem, for instance when calculating widths etc.

![margin](https://cloud.githubusercontent.com/assets/61015/8801576/07b1aeac-2fbc-11e5-91fd-a55f9d973a98.png)

**Comment by nitrada** [comment]
@dinko fixed with https://github.com/preciousforever/sketch-data-populator/commit/5f9dd947fe56bb92f384d0f8750adf3493c5115d

**Comment by nitrada** [comment]
@dinko it's in the "development" branch. could you check it out and let us know if this fix works for you?

**Comment by dinko** [comment]
Sure, will try!

**Comment by dinko** [comment]
The fix works, thx!

**Comment by nitrada** [comment]
@lukas77me can you merge?

**Comment by lukas77me** [comment]
Done
