### ISSUE TITLE
Open last active folder

### ISSUE THREAD

**Issue by dinko** [preciousforever/sketch-data-populator#22]
When using "Populate with JSON" it would be helpful if the last active folder is opened and not the user's home folder.

I understand a folder must be authorized. But when you work on a project and have a specific json file located somewhere, it's quite tedious to always navigate to that specific folder, even if I may have placed it in the sidebar navigation or even though I can find it in the last used folders list.

**Comment by nitrada** [comment]
@lukas77me didn't we fix this for "Place image/SVG"?

**Comment by lukas77me** [comment]
Yes, for place image/svg it remembers the last folder. We can definitely
add it for selecting JSON too.

**Comment by dinko** [comment]
Thx!

**Comment by nitrada** [comment]
That would be useful!

**Comment by nitrada** [comment]
fixed with https://github.com/preciousforever/sketch-data-populator/commit/45f9adceaedf65a2ad37aad041c5e6023095c918

**Comment by dinko** [comment]
Excellent!
