### ISSUE TITLE
Sketch 3.4 Beta bug when populating from JSON/Preset

### ISSUE THREAD

**Issue by justinlwz** [preciousforever/sketch-data-populator#23]

**Comment by nitrada** [comment]
@lukas77me I have not tested with 3.4 beta yet. Did you?

**Comment by lukas77me** [comment]
I just did some testing in 3.4 and it seems to be an issue with how the labels (on the alert) are created. I'll look into it.

**Comment by lukas77me** [comment]
The only solution that works in 3.4 beta I have found is to make the bold labels/titles on the UI regular thickness. The issue seems to be with setting the font for the labels (even just creating an instance of NSFont crashes which is very odd).

**Comment by clarklab** [comment]
Seems like this is still happening. Sketch 3.4 crashes any time I try to populate from JSON (while smaller functions like Place Image work just fine)

**Comment by nitrada** [comment]
@clarklab it seems to work with commands that are not using the plugin UI (see @lukas77me's explanation). we're still investigating, since this bug seems pretty odd.

**Comment by nitrada** [comment]
@justinlwz @clarklab can you try the latest version of the plugin and let us know if the fix works for you guys?

**Comment by justinlwz** [comment]
yup. it worked fine. thanks so much :)
