### ISSUE TITLE
Map specific items in data to specific content variables

### ISSUE THREAD

**Issue by kmerc** [preciousforever/sketch-data-populator#24]
It would be great if we could map items in data to specific content variables? eg {firstname-0} = data[0].firstname

Use case:
Multiple modules (repeated elements) that are disconnected, across multiple artboards, or nested within different symbols but which share common data.

Thanks,

**Comment by nitrada** [comment]
hey @kmerc, does this new release help you? https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.2.1

**Comment by nitrada** [comment]
@kmerc have you figured this out? does the current version of the plugin work for you?

related:
https://github.com/preciousforever/sketch-data-populator/issues/30
https://github.com/preciousforever/sketch-data-populator/issues/34
