### ISSUE TITLE
Ability to interpret nested data

### ISSUE THREAD

**Issue by alexcolbeck** [preciousforever/sketch-data-populator#30]
Will there be an enhancement which enables Sketch to read nested data? Currently it ignores anything that is nested. For example:

```
[

    {
      "id": 1,
      "summary": "Willie",
      "image": "/images/_78419012.jpg",
      "items":[  
               {  
                  "type":"stuff",
                  "title":"stuff",
                  "summary":"stuff",
                  "stuff":false
                  },
      "headline": "stuff",
      "company": "stuff",
      "job": "stuff",
      "email": "stuff"
  ]
```

Thanks!

**Comment by nitrada** [comment]
nested data should be possible since v1.2.1, do you have the latest version of the plugin? https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.2.1

**Comment by nitrada** [comment]
have you figured this out, @alexcolbeck?

**Comment by alexcolbeck** [comment]
I only just realised there is a newer release with this capability in!

Is it possible to create a new release which includes this and the image url link??

**Comment by alexcolbeck** [comment]
Hi - managed to get it working thanks (didnt find the syntax anywhere :+1: )

Thanks again - amazing plugin

**Comment by nitrada** [comment]
yeah, the syntax was only in the release note, not in the readme. will update.
