### ISSUE TITLE
Link images using URL

### ISSUE THREAD

**Issue by alexcolbeck** [preciousforever/sketch-data-populator#31]
Can you link images with URL? i cant seem to get it working.

**Comment by nitrada** [comment]
No, it's not possible and not planned. We prefer to keep all data and assets local for performance reasons.

**Comment by alex-colbeck** [comment]
This plugin does it....
https://github.com/florianpnn/sketch-data-parser

**Comment by nitrada** [comment]
we often use the plugin to populate huge amounts of elements, which can be quite slow already with local images. That's why we're not looking into adding the feature. 

In case you want to give it a try, feel free to add and send a pull request :)

**Comment by alex-colbeck** [comment]
I'll give it a go....if I can work it out ;)

**Comment by alex-colbeck** [comment]
Also if you populate it with huge amounts of elements....have you found a way of adding in loads of local image url's?

only way i can think of doing it is manually....any expert tricks?!

**Comment by nitrada** [comment]
have you tried https://import.io/?

**Comment by nitrada** [comment]
now possible https://github.com/preciousforever/sketch-data-populator/pull/33
