### ISSUE TITLE
Error parsing data

### ISSUE THREAD

**Issue by fortress** [preciousforever/sketch-data-populator#32]
I've seen an error that reads, "There was an error parsing data. Please make sure it's valid."

Just wondering if you could help me understand what's triggering the error and how to fix it.

I've validated the JSON and it works with the plugin until it doesn't. Sometimes a new text box or a new document fixes the issue. The template I have is large so that's not ideal.

Help?

**Comment by nitrada** [comment]
@fortress can you share your sketch and json files with us and let us know which version of sketch and which version of the plugin you're using?
