### ISSUE TITLE
Unintended layer text is changing

### ISSUE THREAD

**Issue by epan** [preciousforever/sketch-data-populator#36]
**What happened**

When I populated a Sketch file with JSON, it is mysteriously also changes other text layers' content even though they are not variables.

The unintended text layers changed are being changed to text that it was before but written over and saved in Sketch.

**What is expected**

The layers with variables will change and the layers without variables will not change. 

**Steps to reproduce**

1. Select all layers
2. Restore Placeholders (optional)
3. Populate data with JSON
4. Select the JSON file
5. See all the layers change, not just the ones referenced in the JSON and the layers with variables

Files to reproduce and screencast of my repro: https://db.tt/vqDH6B74

**Some other notes on the mysterious text layer**

1. When I select the layer and `Restore Placeholders` it doesn't do anything, confirming that it's not working as a variable.
2. There is no text in the JSON file corresponding to the text that the mysterious layer is being replaced with.

Thanks!

**Comment by nitrada** [comment]
@epan thanks for reporting this, very strange and never happened to us. Which version of sketch did you use? Also, did you try to take elements to populate to another sketch document and see what happens there?
