### ISSUE TITLE
Crashes Sketch when dialogue opens

### ISSUE THREAD

**Issue by imvunoah** [preciousforever/sketch-data-populator#37]
When I run the plugin, Sketch crashes as soon at the file chooser dialogue opens.

Running Sketch 3.4.2. Purchased from App Store, but running manually downloaded copy.

Video of crash:
https://dl.dropboxusercontent.com/u/103385876/sketch-json-crash.mp4

**Comment by nitrada** [comment]
It looks like there's a problem with your data. Could you share your JSON file?

Before that: is the content of your "My API" file valid JSON? It should be an array on the root level. Also, please try to call your file "something.json".

**Comment by nipponese** [comment]
@nitrada http://www.exampleapi.com/json

**Comment by imvunoah** [comment]
@nitrada I saved the output from this to a file: http://www.exampleapi.com/json

**Comment by nitrada** [comment]
@imvunoah 

I just checked the output and as expected, the JSON was missing an array on the root level: the ```[]``` brackets (check out [this JSON primer](https://adobe.github.io/Spry/articles/json_primer/json_primer.html) for more detailed info). Also, please use **.json** at the end of your file.

here's your example data with the root array added:

```json
[{
  "id": "49020834",
  "title": "My First Post Sample",
  "slug": "my-first-post-sample",
  "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit…",
  "date-created": "2013-03-26-13-59-59",
  "date-modified": "2013-04-09-15-01-49",
  "thumbnail": "http://lorempixel.com/400/400",
  "tags": "web development, api, demo, example, node"
}]
```
This if how it would look like if there's more than one object in the array:

```json
[{
  "id": "49020834",
  "title": "My First Post Sample",
  "slug": "my-first-post-sample",
  "content": "Lorem ipsum dolor sit amet, consectetur adipisicing elit…",
  "date-created": "2013-03-26-13-59-59",
  "date-modified": "2013-04-09-15-01-49",
  "thumbnail": "http://lorempixel.com/400/400",
  "tags": "web development, api, demo, example, node"
},
{
  "id": "49020835",
  "title": "My Second Post Sample",
  "slug": "my-second-post-sample",
  "content": "Dolor dicta in at error ipsam vel ipsum odit tempora ipsa nulla facere…",
  "date-created": "2013-03-26-14-00-00",
  "date-modified": "2013-04-09-15-01-50",
  "thumbnail": "http://lorempixel.com/401/401",
  "tags": "web development, api, demo, example, node"
}]
```
hope this helps. I tested the JSON on my end and it worked.

**Comment by imvunoah** [comment]
@nitrada What is the reason for the root array? I've never seen valid JSON enclosed in an array like that, and even in your examples it seems redundant since there is only one element which stores every object.

**Comment by nitrada** [comment]
Which example do you mean?

Our JSON data usually consist of dozens or hundreds of objects and we preferred to put them in an array on the root level. 

We could consider making it work without an array if there's only one object – or even if there's a list of objects. It's a matter of taste probably. What do you think, @lukas77me?

**Comment by lukas77me** [comment]
I agree that it'll make it more intuitive if you only have a single object
in the JSON. I can take a look at this.

**Comment by nitrada** [comment]
@imvunoah apart from that, does adding the array fix it for you for now?

**Comment by imvunoah** [comment]
Guys, just loaded up the original json file (without the single-element array) and it works great. Thank you!
