### ISSUE TITLE
Populate with JSON only uses text from 2nd data set

### ISSUE THREAD

**Issue by daniloq** [preciousforever/sketch-data-populator#39]
I have the json file below filled with different assets and text. When I use populate with JSON and say I need 1 column and 2 rows, I get two layer groups with two different avatars, but each layer group uses the same placeholder text from ID 2 only.

[
  {
    "id": 1,
    "avatar" : "URL1",
    "name": "NAME1",
    "location": "LOCATION1"
  },
  {
    "id": 2,
    "avatar" : "URL2",
    "name": "NAME2",
    "location": "LOCATION2"
  
]

**Comment by nitrada** [comment]
@daniloq is the JSON you pasted here exactly the one you used? there's a closing curly bracket (}) missing in the second object (id 2). Maybe that's the problem?

**Comment by daniloq** [comment]
@nitrada Oops. Sorry for the typo. Here's what I'm using. 

[{
  "name": "Pete Wrigley",
  "image": "http://www.radfaces.com/images/avatars/little-pete-wrigley.png",
  "location": "Wellsville, NY"
}, {
  "name": "Aeon Flux",
  "image": "http://www.radfaces.com/images/avatars/aeon-flux.png",
  "location": "Nation of Monica"
}, {
  "name": "Alan Frog",
  "image": "http://www.radfaces.com/images/avatars/alan-frog.png",
  "location": "Santa Clara, CA"
}, {
  "name": "Amanda Bynes",
  "image": "http://www.radfaces.com/images/avatars/amanda-bynes.png",
  "location": "Hollywood, CA"
}, {
  "name": "April O'Neil",
  "image": "http://www.radfaces.com/images/avatars/april-oneil.png",
  "location": "Brooklyn, NY"
}, {
  "name": "Artie - the strongest man in the world!",
  "image": "http://www.radfaces.com/images/avatars/artie-strongman.png",
  "location": "Wellsville, NY"
}, {
  "name": "Baby Sinclair",
  "image": "http://www.radfaces.com/images/avatars/baby-sinclair.png",
  "location": "Pangaea"
}, {
  "name": "Big Pete Wrigley",
  "image": "http://www.radfaces.com/images/avatars/big-pete-wrigley.png",
  "location": "Wellsville, NY"
}, {
  "name": "Bobby Budnick",
  "image": "http://www.radfaces.com/images/avatars/bobby-budnick.png",
  "location": "Camp Anawanna, VA"
}, {
  "name": "Bradley Taylor",
  "image": "http://www.radfaces.com/images/avatars/bradley-taylor.png",
  "location": "Dude Ranch, AZ"
}, {
  "name": "Casey Jones",
  "image": "http://www.radfaces.com/images/avatars/casey-jones.png",
  "location": "Brooklyn, NY"
}, {
  "name": "Charlene Sinclair",
  "image": "http://www.radfaces.com/images/avatars/charlene-sinclair.png",
  "location": "Pangaea"
}, {
  "name": "Chris Chambers",
  "image": "http://www.radfaces.com/images/avatars/chris-chambers.png",
  "location": "Castlerock, OR"
}, {
  "name": "Danny Lightfoot",
  "image": "http://www.radfaces.com/images/avatars/danny-lightfoot.png",
  "location": "Dude Ranch, AZ"
}, {
  "name": "Danny Pennington",
  "image": "http://www.radfaces.com/images/avatars/danny-pennington.png",
  "location": "Brooklyn, NY"
}, {
  "name": "Daria Morgendorffer",
  "image": "http://www.radfaces.com/images/avatars/daria-morgendorffer.png",
  "location": "Lawndale, MTV"
}, {
  "name": "Dina Alexander",
  "image": "http://www.radfaces.com/images/avatars/dina-alexander.png",
  "location": "Camp Anawanna, VA"
}, {
  "name": "Eddie Gelfen",
  "image": "http://www.radfaces.com/images/avatars/eddie-gelfen.png",
  "location": "Camp Anawanna, VA"
}, {
  "name": "Ellen Josephine Hickle",
  "image": "http://www.radfaces.com/images/avatars/ellen-josephine-hickle.png",
  "location": "Wellsville, NY"
}, {
  "name": "Ernest Worrell",
  "image": "http://www.radfaces.com/images/avatars/ernest-worrell.png",
  "location": "Jail, Prison"
}, {
  "name": "Harriet Welsch",
  "image": "http://www.radfaces.com/images/avatars/harriet-welsch.png",
  "location": "Upper East Side, NY"
}, {
  "name": "Ickis",
  "image": "http://www.radfaces.com/images/avatars/ickis.png",
  "location": "City Dump, NY"
}, {
  "name": "Jane Lane",
  "image": "http://www.radfaces.com/images/avatars/jane-lane.png",
  "location": "Lawndale, MTV"
}, {
  "name": "Jeffrey Douglas",
  "image": "http://www.radfaces.com/images/avatars/jeffrey-douglas.png",
  "location": "Pasadena, CA"
}, {
  "name": "Kel Mitchell",
  "image": "http://www.radfaces.com/images/avatars/kel-mitchell.png",
  "location": "Hollywood, CA"
}, {
  "name": "Krumm",
  "image": "http://www.radfaces.com/images/avatars/krumm.png",
  "location": "City Dump, NY"
}, {
  "name": "Lawrence Cohen",
  "image": "http://www.radfaces.com/images/avatars/lawrence-cohen.png",
  "location": "Astoria, OR"
}, {
  "name": "Lori-Beth Denberg",
  "image": "http://www.radfaces.com/images/avatars/lori-beth-denberg.png",
  "location": "Hollywood, CA"
}, {
  "name": "Marshall Teller",
  "image": "http://www.radfaces.com/images/avatars/marshall-teller.png",
  "location": "Eerie, IN"
}, {
  "name": "Mechagodzilla",
  "image": "http://www.radfaces.com/images/avatars/mechagodzilla.png",
  "location": "Tokyo, Japan"
}, {
  "name": "Melody Hanson",
  "image": "http://www.radfaces.com/images/avatars/melody-hanson.png",
  "location": "Dude Ranch, AZ"
}, {
  "name": "Michael Douglas",
  "image": "http://www.radfaces.com/images/avatars/michael-douglas.png",
  "location": "Pasadena, CA"
}, {
  "name": "Michael Walsh",
  "image": "http://www.radfaces.com/images/avatars/michael-walsh.png",
  "location": "Astoria, OR"
}, {
  "name": "Michelangelo",
  "image": "http://www.radfaces.com/images/avatars/michelangelo.png",
  "location": "Brooklyn, NY"
}, {
  "name": "Oblina",
  "image": "http://www.radfaces.com/images/avatars/oblina.png",
  "location": "City Dump, NY"
}, {
  "name": "Patty Mayonnaise",
  "image": "http://www.radfaces.com/images/avatars/patty-mayonnaise.png",
  "location": "Bluffington, VA"
}, {
  "name": "Powdered Toast Man",
  "image": "http://www.radfaces.com/images/avatars/powdered-toast-man.png",
  "location": "City Hicks, TN"
}, {
  "name": "Quinn Morgendorffer",
  "image": "http://www.radfaces.com/images/avatars/quinn-morgendorffer.png",
  "location": "Lawndale, MTV"
}, {
  "name": "Reno Reyes, Jr.",
  "image": "http://www.radfaces.com/images/avatars/reno-reyes-jr.png",
  "location": "Brooklyn, NY"
}, {
  "name": "Richard Wang",
  "image": "http://www.radfaces.com/images/avatars/richard-wang.png",
  "location": "Astoria, OR"
}, {
  "name": "Robbie Sinclair",
  "image": "http://www.radfaces.com/images/avatars/robbie-sinclair.png",
  "location": "Pangaea"
}, {
  "name": "Roger Klotz",
  "image": "http://www.radfaces.com/images/avatars/roger-klotz.png",
  "location": "Bluffington, VA"
}, {
  "name": "Sam Emerson",
  "image": "http://www.radfaces.com/images/avatars/sam-emerson.png",
  "location": "Santa Clara, CA"
}, {
  "name": "Samuel Douglas",
  "image": "http://www.radfaces.com/images/avatars/samuel-douglas.png",
  "location": "Pasadena, CA"
}, {
  "name": "Simon Holmes",
  "image": "http://www.radfaces.com/images/avatars/simon-holmes.png",
  "location": "Eerie, IN"
}, {
  "name": "Skeeter Valentine",
  "image": "http://www.radfaces.com/images/avatars/skeeter-valentine.png",
  "location": "Bluffington, VA"
}, {
  "name": "Star Emerson",
  "image": "http://www.radfaces.com/images/avatars/star-emerson.png",
  "location": "Santa Clara, CA"
}, {
  "name": "Teddy Duchamp",
  "image": "http://www.radfaces.com/images/avatars/teddy-duchamp.png",
  "location": "Castlerock, OR"
}, {
  "name": "Telly Radford",
  "image": "http://www.radfaces.com/images/avatars/telly-radford.png",
  "location": "Camp Anawanna, VA"
}, {
  "name": "Trent Lane",
  "image": "http://www.radfaces.com/images/avatars/trent-lane.png",
  "location": "Lawndale, MTV"
}, {
  "name": "Vern Tessio",
  "image": "http://www.radfaces.com/images/avatars/vern-tessio.png",
  "location": "Castlerock, OR"
}, {
  "name": "Alex Murphy",
  "image": "http://www.radfaces.com/images/avatars/alex-murphy.png",
  "location": "Detroit, MI"
}, {
  "name": "Atreyu",
  "image": "http://www.radfaces.com/images/avatars/atreyu.png",
  "location": "Fantastica"
}, {
  "name": "Bill Esquire",
  "image": "http://www.radfaces.com/images/avatars/bill-esquire.png",
  "location": "San Dimas, CA"
}, {
  "name": "Bishop",
  "image": "http://www.radfaces.com/images/avatars/bishop.png",
  "location": "Queens, NY"
}, {
  "name": "David Bowie",
  "image": "http://www.radfaces.com/images/avatars/david-bowie.png",
  "location": "The Labyrinth"
}, {
  "name": "Empress Tami",
  "image": "http://www.radfaces.com/images/avatars/empress-tami.png",
  "location": "Fantastica"
}, {
  "name": "Iggy",
  "image": "http://www.radfaces.com/images/avatars/iggy.png",
  "location": "Surf City, CA"
}, {
  "name": "Kennedy Montgomery",
  "image": "http://www.radfaces.com/images/avatars/kennedy-montgomery.png",
  "location": "MTV News, MTV"
}, {
  "name": "Link",
  "image": "http://www.radfaces.com/images/avatars/link.png",
  "location": "Encino, CA"
}, {
  "name": "Pat Benetar",
  "image": "http://www.radfaces.com/images/avatars/pat-benatar.png",
  "location": "Brooklyn, NY"
}, {
  "name": "Sarah Williams",
  "image": "http://www.radfaces.com/images/avatars/sarah-williams.png",
  "location": "The Labyrinth"
}, {
  "name": "Stoney Brown",
  "image": "http://www.radfaces.com/images/avatars/stoney-brown.png",
  "location": "Encino, CA"
}, {
  "name": "Ted Logan",
  "image": "http://www.radfaces.com/images/avatars/ted-logan.png",
  "location": "San Dimas, CA"
}, {
  "name": "Vera De Milo",
  "image": "http://www.radfaces.com/images/avatars/vera-de-milo.png",
  "location": "In Living Color, TV"
}, {
  "name": "Yellow Frog",
  "image": "http://www.radfaces.com/images/avatars/yellow-frog.png",
  "location": "Hidden Temple"
}, {
  "name": "Asha Kuerten",
  "image": "http://www.radfaces.com/images/avatars/asha-kuerten.png",
  "location": "Guts, Australia"
}, {
  "name": "Elvira Hancock",
  "image": "http://www.radfaces.com/images/avatars/elvira-hancock.png",
  "location": "Miami, FL"
}, {
  "name": "June",
  "image": "http://www.radfaces.com/images/avatars/june.png",
  "location": "KaBlam, Nick"
}, {
  "name": "Alex Mack",
  "image": "http://www.radfaces.com/images/avatars/alex-mack.png",
  "location": "Paradise Valley, CA"
}, {
  "name": "Clarissa Marie Darling",
  "image": "http://www.radfaces.com/images/avatars/clarissa-marie-darling.png",
  "location": "Smalltown, OH"
}, {
  "name": "Dylan McKay",
  "image": "http://www.radfaces.com/images/avatars/dylan-mckay.png",
  "location": "Beverly Hills, CA 90210"
}, {
  "name": "Kelly Kapowski",
  "image": "http://www.radfaces.com/images/avatars/kelly-kapowski.png",
  "location": "Bayside High"
}, {
  "name": "Kimmy Gibbler",
  "image": "http://www.radfaces.com/images/avatars/kimmy-gibbler.png",
  "location": "San Francisco, CA"
}, {
  "name": "Scrappy-Doo",
  "image": "http://www.radfaces.com/images/avatars/scrappy-doo.png",
  "location": "Crystal Cove"
}, {
  "name": "Tina Carlyle",
  "image": "http://www.radfaces.com/images/avatars/tina-carlyle.png",
  "location": "Edge City"
}, {
  "name": "Zack Taylor",
  "image": "http://www.radfaces.com/images/avatars/zack-taylor.png",
  "location": "Angel Grove"
}, {
  "name": "Will Smith",
  "image": "http://www.radfaces.com/images/avatars/will-smith.png",
  "location": "Bel Air, Ca"
}, {
  "name": "Rufio",
  "image": "http://www.radfaces.com/images/avatars/rufio.png",
  "location": "Neverland"
}, {
  "name": "Chucky",
  "image": "http://www.radfaces.com/images/avatars/chucky.png",
  "location": "Yucaipa, CA"
}]

**Comment by nitrada** [comment]
@daniloq I just tried with you data and it worked fine. btw, the populating is much faster if your images are locally stored in a subfolder…

do you have your sketch layers containing "{name}", "{image}" and {location} in a layer group each, all on the same level?

**Comment by daniloq** [comment]
Thanks @nitrada.
