### ISSUE TITLE
presets

### ISSUE THREAD

**Issue by nitrada** [preciousforever/sketch-data-populator#4]
have a "presets" folder in the plugin folder where you can move the JSON files. then, when running the plugin, it will give you a dialog to choose from those files (compare color palettes plugin)

it should still be possible to "import" any JSON from anywhere

**Comment by lukas77me** [comment]
There is now a 'Presets' folder in the plugin bundle and nested folders are also supported. When selecting the presets on the new UI panel, nested presets are shown like 'folder/subfolder/my-preset'.
