### ISSUE TITLE
populate symbols with different images

### ISSUE THREAD

**Issue by leffi7** [preciousforever/sketch-data-populator#40]
Hi,

When sketching a blog archive page, I create a symbol for a blogpost. A blogpost generally contains a title, excerpt/description and an image.

I know it is possible in Sketch to 'exclude text value from symbol'. This way every post gets its own title. But is there also a way to exclude an image? I'm not sure if this is a feature missing in Sketch or a feature request for the plugin.

Do you see any options how to deal with this?

thx!

**Comment by nitrada** [comment]
That's a sketch feature request :)

**Comment by leffi7** [comment]
Hehe... What I thought :)

Any ideas on a workaround?

Anyway, will keep using your plugin cause it is great! Nice work! Thx!

Verstuurd vanaf mijn iPhone

**Comment by nitrada** [comment]
@leffi7 the only workaround is not using a symbol ;-) have you tried using styles instead of a symbol, or a different nesting?

**Comment by leffi7** [comment]
OK :)

I guess there is no other option than using 'normal' groups.

thx for your feedback!

2015-12-07 20:25 GMT+01:00 Christophe Stoll <notifications@github.com>:
