### ISSUE TITLE
Writing out items in reverse order

### ISSUE THREAD

**Issue by gunkdesign** [preciousforever/sketch-data-populator#44]
Hi there,

I am using the populator to write out a list of sports in a text variable {sport}, these layers sit in a group that I have duplicated 27 times as there is other items in the group.

When I run the populator two things happen.
1. The items write out in reverse order
2. At the end of the loop it jumps to the next page in sketch (have to go back in the navigator)
[data-populator issue.zip](https://github.com/preciousforever/sketch-data-populator/files/96091/data-populator.issue.zip)

**Comment by nitrada** [comment]
@gunkdesign does it work with the latest version of the plugin? https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.7.0
