### ISSUE TITLE
Not recognising nested data

### ISSUE THREAD

**Issue by alex-colbeck** [preciousforever/sketch-data-populator#45]
For some reason it no longer allows me to use nested JSON.

For example:

    "categories": [
      {
        "id": 8,
        "name": "News",
      }
    ],

It would normally allow me to just use {categories.name}

**Comment by nitrada** [comment]
@alex-colbeck this is how you address arrays properly:
https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.3.0

{categories.name} would work if you'd have nested objects, not an array within an object. am I right @rockitbaby?

does this solve it for you, @alex-colbeck?

**Comment by rockitbaby** [comment]
`{categories[0].name}` should work

**Comment by alex-colbeck** [comment]
Ace!!! 

Thanks very much
