### ISSUE TITLE
Images/image url issue

### ISSUE THREAD

**Issue by deepesh55** [preciousforever/sketch-data-populator#46]
The textual contents are getting placed perfectly well, but the images remain the same. You can see if below that I have specified a different picture for each section but still in the end when I run the script in Sketch, it brings out only one of those images and on every "Populate again" command it just brings another picture but the same for everything.

I just started using this plugin so is there anything else I should be looking for ?

[
    {
      "course names" : "Cosmetic Dentistry",
      "date" : "3 Mar 2016",
      "price" : "Rs. 40,000",
      "image" : "Informdoc iOS/images/File1.jpg"
    },
    {
      "course names" : "State of the art Endodontics for the General Practitioner",
      "date" : "NIL",
      "price" : "Rs. 20,000",
      "image" : "Informdoc iOS/images/File2.jpg"
    },
    {
      "course names" : "Crown and Bridge",
      "date" : "20 Feb 2016",
      "price" : 15000,
      "image" : "Informdoc iOS/images/File3.jpg"
    },
    {
      "course names" : "Laser Dentistry",
      "date" : "NIL",
      "price" : 15000,
      "image" : "Informdoc iOS/images/File4.jpg"
    },
    {
      "course names" : "BPS Denture",
      "date" : "13 Mar 2016",
      "price" : 15000,
      "image" : "Informdoc iOS/images/File5.jpg"
    },
    {
      "course names" : "Certificate Program in Clinical Dentistry",
      "date" : "09 Apr 2016",
      "price" : 180000,
      "image" : "Informdoc iOS/images/File6.png"
    }
  ]

**Comment by nitrada** [comment]
@deepesh55 can you send your sketch file to feedback@datapopulator.com?

**Comment by alex-colbeck** [comment]
Images aren't loading for me either. They worked perfectly before the 3.5.1 update and now dont fill.

I am using image url for achieve this.

I have updated to the latest release - any idea why this is happening?

**Comment by nitrada** [comment]
@alex-colbeck can you share an excerpt of your JSON?

**Comment by alex-colbeck** [comment]
[
  {
    "facebookAuthor": "https://www.facebook.com/facebook-author",
    "id": "4156465464644-id-here",
    "title": "Title here",
    "image": "http://image-url-here.png"
  },
  {
    "facebookAuthor": "https://www.facebook.com/facebook-author",
    "id": "4156465464644-id-here",
    "title": "Title here",
    "image": "http://image-url-here.png"
  },
  {
    "facebookAuthor": "https://www.facebook.com/facebook-author",
    "id": "4156465464644-id-here",
    "title": "Title here",
    "image": "http://image-url-here.png"
  },
  {
    "facebookAuthor": "https://www.facebook.com/facebook-author",
    "id": "4156465464644-id-here",
    "title": "Title here",
    "image": "http://image-url-here.png"
  }
]

**Comment by alex-colbeck** [comment]
Any updates on this @nitrada  ?

**Comment by lukasondrej** [comment]
@alex-colbeck I've just fixed an issue with images when using urls. Please give it a go and let us know if it works for you. Thanks

**Comment by alex-colbeck** [comment]
Thanks @lukasondrej  - Can you send me a link to this release/zip?

**Comment by nitrada** [comment]
is the issue fixed for you as well, @deepesh55?
