### ISSUE TITLE
Make Grid and Sketch 3.5

### ISSUE THREAD

**Issue by dantz** [preciousforever/sketch-data-populator#47]
I can fill a single row but as soon as I try to make a grid placeholders aren't replaced anymore.

**Comment by nitrada** [comment]
we're investigating.

**Comment by dantz** [comment]
But you can reproduce it? After downgrading to 3.4.4 it works again. Unfortunately my document does not :)

**Comment by lukasondrej** [comment]
Please try the version in the `sketch-3.5-support` branch with Sketch 3.5. It should hopefully work as expected.

**Comment by bdenham** [comment]
Awesome, guys! I just confirmed that it does indeed work as expected. Many thanks!
