### ISSUE TITLE
Images/Icons also not populating in Sketch 3.5.1

### ISSUE THREAD

**Issue by bdenham** [preciousforever/sketch-data-populator#48]
In addition to the Make Grid issue, the {image} and {{icon}} placeholders are also not working. You can see the behavior from the demo.sketch file. I'm sure you guys noticed this as well (hard to miss). But I wanted to mention it as another breaking change with Sketch 3.5.1.

**Comment by lukasondrej** [comment]
Thanks for reporting this. Please try the version in the `sketch-3.5-support` branch which addresses these issues. It'd be much appreciated if you could let us know if it works for you.

**Comment by denswor** [comment]
Hi guys, `sketch-3.5-support` works fine in sketch 3.5.1

Thanks!

**Comment by bdenham** [comment]
Confirmed. All is working well again. Thanks for responding and fixing so quickly!
