### ISSUE TITLE
icon "placeholder"

### ISSUE THREAD

**Issue by nitrada** [preciousforever/sketch-data-populator#5]
scenario: in the data, you say eg. "icon": "email". in the sketch template you have a placeholder boundingBox with the desired size called "icon". the plugin looks up another sketch file and grabs a layer group (containing the mail icon as vector) called "email" and inserts the appropriate icon.

(i think it's not really possible technically, since generally speaking, this would be a great solution to "import" UI components/icons in a very meaningful way and somebody would have done that already ;-)

**Comment by nitrada** [comment]
we're currently using pngs for icons as well. would already be great to use svgs instead so the colors are flexible. 

A svg couldn't be used as a rectangle background though. an idea: we set a placeholder icon in the desired size and color and replace it with the svg asset. The size and color should be adapted programmatically.

**Comment by z-vector** [comment]
Is this feature works?
I try use icon placeholder {{icon}}, but strange things happens.
Also if you try to use .svg for {icon} it crashes Sketch.

**Comment by nitrada** [comment]
@z-vector could you specify "strange things"?

**Comment by z-vector** [comment]
For example I have {image} layer + "{text1}" + "{text2}" + {{icon}} layers.
After populate, it fills different pics into {image} for a second and then saddenly fills all {images} whith only one pic for all {image} containers + fills all {{icon}} with the same pic.

**Comment by nitrada** [comment]
Select all groups that contain the placeholders. for example, selecting the parent group or artboard would lead to populating the same dataset to all children.

Also make sure the groups you populate with images or icons are no symbols. otherwise, they will be synced, just like all other elements in symbols (apart from text, which can be excluded).

**Comment by z-vector** [comment]
Yep, I'v done all like you said. But {{icon}} placeholder does not work at all. And strange behaviour for groups with {{icon}} like I describe before.
Also I try groups with only {{icon}}+{text} placehoders, but it is crash Sketch.
