### ISSUE TITLE
Sketch Crash on Populate With JSON when using SVG

### ISSUE THREAD

**Issue by bgohsman** [preciousforever/sketch-data-populator#50]
It took me a few minutes to track down, but I am running into an issue where, if I use the SVG version of an icon, Sketch will crash upon clicking the "Populate" button. However, if I use a PNG version of the same icon, everything goes swimmingly. 

The SVG in question was originally generated by Sketch. I also attempted re-saving it from Illustrator as an SVG. And, then, exporting it from Illustrator as a web-optimized SVG. Same results. I also tried a few different SVG icons in case it was specific to one odd/corrupt file. Below is the actual SVG text of the SVG generated by Sketch:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="21px" height="18px" viewBox="0 0 21 18" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>icon_checkmark_green</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="Response-States" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="UI-Components" transform="translate(-532.000000, -50.000000)" fill="#5BB55D">
            <path d="M538.82094,67.1223958 L532,58.1380208 L535.024379,54.9479167 L538.82094,59.8307292 L550.725412,50 L552.205427,51.4973958 L538.82094,67.1223958 L538.82094,67.1223958 Z" id="icon_checkmark_green"></path>
        </g>
    </g>
</svg>`

**Comment by bgohsman** [comment]
I believe I have figured out what I am doing wrong. Looking at only one demo, I assumed that SVGs were treated the same as any other image type and, as such, would use the same placeholder. However, looking through the code for populate(), I found that it looks for specific iconPlaceholders with the pattern {{*}}. Which tells me that I probably need double curly brackets on my placeholders for SVGs. I'll make that change later this afternoon and see how it goes.

**Comment by bgohsman** [comment]
Using the example from _demo.sketch_ [the icon on a ListItem in the "contacts" example] definitely behaved differently, but Sketch still crashed. I could see the rows get generated. I could see the icon placeholders but the actual SVG icon did not load into them. The view appeared to zoom out, almost as if I'd hit Command + 1. And then Sketch crashed. For the moment, I'm just going to use PNG versions of the icons and generate SVG assets for development. 

If it helps, I am running Sketch 3.6.1 (26313) on El Capitan 10.11.3.

**Comment by nitrada** [comment]
Yeah, it's double brackets. But also, the SVG stuff is a bit shaky, since loading external SVGs is more complex than loading an image.

**Comment by bgohsman** [comment]
That makes sense. For our purposes, it's working great just using PNG files. Then we export icons as SVG for the dev team. This has already saved hours as design iteration progresses. Being able to update a single object and then re-populate a layout [in my case, a table full of rows of data] has been a very good thing.
