### ISSUE TITLE
Creating data visualizations in Sketch

### ISSUE THREAD

**Issue by hungrysquirrel** [preciousforever/sketch-data-populator#51]
<img width="680" alt="visualizing_data" src="https://cloud.githubusercontent.com/assets/232397/14184841/056b12d6-f72c-11e5-81e2-5727a181b1a8.png">

I’ve used https://github.com/preciousforever/sketch-data-populator for Sketch and run into a blocker for me. I am parsing SVG graphics to points on the artboard and I was hoping to pass in a radius or W x H (in JSON) to the containers on the artboard that hold the svg’s in hopes to control their scale.

Currently the container on the artboard restricts the real proportions I need translated. Can Sketch layer properties be accessed in the JSON data import so I can control the SVG container size?

**Comment by rhythmspice** [comment]
I second this request! I just want to be able to control a list of bar charts (rectangle objects) by passing in the widths from JSON values.

**Comment by nitrada** [comment]
that's nothing we're going to implement in the near future, but feel free to contribute :-)
