### ISSUE TITLE
v1.6-beta.1: Can't save file after feeding symbols with JSON…

### ISSUE THREAD

**Issue by F-DK** [preciousforever/sketch-data-populator#56]
After creating a list of items in Sketch 3.7 (28169) from a (new 3.7 type) symbol by importing a (tested and error free) JSON file I cannot save the document. That makes Data Populator completely useless for symbols – which let's me stuck in Sketch 3.6.1 :/

Data Populator 1.6-beta.1 (with JSON import) only works with regular folders, not with symbols as far as I experienced it.
Unfortunately I cannot share the files since they are confidential.

Hope it helps,
Aki

**Comment by nitrada** [comment]
@lukasondrej can you reproduce this? it happened to me as well. Can send you the doc.

**Comment by lukasondrej** [comment]
I've tried reproducing this but with no luck. The doc where this happens would be very useful.

**Comment by F-DK** [comment]
Sorry but can't share the file b/c it's confidential.

**Comment by nitrada** [comment]
I will share my doc later today.

**Comment by nitrada** [comment]
I will share my doc later today.

**Comment by nitrada** [comment]
@F-DK can you try the new version? https://github.com/preciousforever/sketch-data-populator/commit/6ef513309e51ff151cdb2b8945b7e495a7d089b7

**Comment by F-DK** [comment]
@nitrada Thanks, but I guess I'm not coder enough to make use of it without stumbeling upon some questions – since there no new beta release available yet…

Can I just download and replace the files after deleting the *.txt file extenision (in the download dialog)?

**Comment by F-DK** [comment]
@nitrada Update: In the 1st test run it worked out fine.

**Comment by nitrada** [comment]
here's a new pre release:
https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.6-beta.2

I recommend you use this version in parallel by renaming a) the bundle file and b) the "name" field in "manifest.json" within the plugin bundle ("Show Content" on "Sketch Data Populator.sketchplugin" plugin bundle).

**Comment by F-DK** [comment]
@nitrada I didn't manage to run both plugins (current and beta.2) in parallel.

This is wat I did:

- Renamed the beta.2 bundle to "Sketch Data Populator Beta.sketchplugin"

- Added the new beta.2 bundle along with the current one

- Changed line 2 in –/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Sketch Data Populator Beta.sketchplugin/Contents/Sketch/manifest.json to `"name": "Sketch Data Populator Beta",`

Result:

- Only the beta.2 is running

Would be great to be able to run both in parallel though.

**Comment by nitrada** [comment]
@F-DK https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.6-beta.3

**Comment by F-DK** [comment]
@nitrada Thank you! 1st test run worked fine 👍
