### ISSUE TITLE
Incorrect image URL = Sketch fails and closes

### ISSUE THREAD

**Issue by r-ss-ll** [preciousforever/sketch-data-populator#57]
I accidentally had the wrong file path in my json. Upon populating with the incorrect image URL Sketch freezes up then closes leaving some temporary pages open in my doc.

**Comment by nitrada** [comment]
@r-ss-ll you populated symbols (in sketch 3.7), right?

**Comment by lukasondrej** [comment]
@r-ss-ll this should be fixed now, please check out the latest commit.

**Comment by r-ss-ll** [comment]
@nitrada That was correct. Great work.
