### ISSUE TITLE
v1.6-beta.2: Text Substitutes don't work as expected in symbols

### ISSUE THREAD

**Issue by nitrada** [preciousforever/sketch-data-populator#58]
when using Text Placeholders a la ```{placeholder?}``` that should be substituted with the default substitute, Sketch 3.7.1 crashes when using the "missing-data" Preset that comes with the demo.

**Comment by nitrada** [comment]
here's a test file – try populating the "item two" symbol with the "missing-data" preset that comes with the demo. re-populate until you run into an empty field.

[datapop new symbols.sketch.zip](https://github.com/preciousforever/sketch-data-populator/files/229333/datapop.new.symbols.sketch.zip)

**Comment by lukasondrej** [comment]
@nitrada in my testing, substitutes worked without any issues however I've found another issue with missing/invalid image URLs when populating symbols. This could be the cause of the crashes - fixed in the latest commit.

**Comment by nitrada** [comment]
@lukasondrej will check.

**Comment by nitrada** [comment]
@lukasondrej seems to work now. the text formating behavior is a bit strange still, will go into detail sometime later. https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.6-beta.3
