### ISSUE TITLE
Multiline text box

### ISSUE THREAD

**Issue by russgoodman** [preciousforever/sketch-data-populator#59]
How do I go about getting three or four lines of text in a box? I can't make the text box three or four lines tall so that it fills.

**Comment by nitrada** [comment]
multiline text is not yet supported as it involves the rather complex topic of "flow layouting"…

**Comment by PDXIII** [comment]
I found a workaround. You create a text object follow the naming conventions set it on fixed and then insert as many line breaks (enter) as you wish. Maybe this helps.

**Comment by nitrada** [comment]
@russgoodman @PDXIII multi line text is now possible, but not yet documented. We'll update the readme/documentation in the first week of January.

Short version: 
append a Layer name (in the LAyers Inspector) with `-l n`  — set `n` as the max number of lines in a fixed size text layer. For example, `Layer name | -l 3` will turn the Text Layer into a box with 3 lines (if there's enough data).

**Comment by nitrada** [comment]
now documented in the https://github.com/preciousforever/sketch-data-populator/blob/master/README.md

a better demo.sketch will follow.

**Comment by lajlev** [comment]
I really struggle to make it work. Would some elaborate on how they got it working 😢

**Comment by francesyun** [comment]
I don't think this is working 🤷‍♂️

**Comment by MDBas** [comment]
Make sure 'Trim overflowing text' is checked.
![image](https://user-images.githubusercontent.com/12843221/45489978-2e87d080-b766-11e8-86a3-db763b1e08e7.png)
