### ISSUE TITLE
hierarchical data/layer structures

### ISSUE THREAD

**Issue by nitrada** [preciousforever/sketch-data-populator#6]
the data hierarchy
```
* group1
  * item1
  * item2
  * item3
* group2
  * item1
  * item2
  * item3
…
```
could be matched to the following layer hierarchy
```
* layergroupA
   * layergroup1
   * layergroup2
   * layergroup3
* layergroupB
   * layergroup1
   * layergroup2
   * layergroup3
```
meaning that {placeholders} will only be replaced on the respective level of the hierarchy

**Comment by VinSpee** [comment]
this would be rad!

**Comment by fculshaw** [comment]
I'm dealing with a JSON file with a lot of levels of objects and It would be really great if this type of file was supported, for example:

   "images":{  
              "landscape":{  
                 "landscape-01":"assets/landscape.jpg",
                 "landscape-02":"assets/landscape-02.jpg"
              },
              "portrait":{  
                 "portrait-01":"assets/portrait-01.jpg",
                 "portrait-02":"assets/portrait-02.jpg"
              },
              "logo":{  
                 "logo-01":"assets/logo-01.jpg",
                 "logo-02":"assets/logo-02.jpg"               
              },
              "background":{  
                 "background-01":"assets/bg-01.jpg",
                 "background-02":"assets/bg-02.jpg"
              }

Apologies if this is already possible, I couldn't seem to get results

**Comment by nitrada** [comment]
@fculshaw this is not yet possible but exactly what we need. :)

**Comment by clarklab** [comment]
+1 for this idea. Currently it seems like all data needs to have the same types/fields, but it would be **hugely** useful to have some asymmetrical datasets.

**Comment by theoBLT** [comment]
+1 for this idea too, multiple object level support would be awesome and make this plugin really cool.

**Comment by nitrada** [comment]
@VinSpee @fculshaw @clarklab @theoBLT 
Since [v1.3.0](https://github.com/preciousforever/sketch-data-populator/releases/tag/v1.3.0), this is fully supported, including nested arrays. Please let us know if you run into issues.
