### ISSUE TITLE
Image URL not populating.

### ISSUE THREAD

**Issue by joshhillier** [preciousforever/sketch-data-populator#62]
Example JSON
```
[
  {
    "hero":"http://www.mountain.org/sites/default/files/image_assets/5920447977_f84dff5a33_o_cropped_0.jpg"
    }
]
```

It seems that it's not populating,
<img width="1504" alt="screen shot 2016-06-02 at 11 22 28" src="https://cloud.githubusercontent.com/assets/6906867/15742156/2565f6a4-28b5-11e6-99b3-d1a4bea8ede2.png">

Any ideas? Sketch version is Version 3.8.3 (29802)

**Comment by amilajack** [comment]
I think that the plugin can't populate data from remote sources. The example shows accessing a local assets directory.

**Comment by amilajack** [comment]
preciousforever/sketch-data-populator/issues/31

**Comment by joshhillier** [comment]
Correct me if I'm wrong, but I believe this features is possible...

https://github.com/preciousforever/sketch-data-populator/pull/33

**Comment by amilajack** [comment]
Apparently it is (or was). But last week I was using this plugin to populate remote images and it didn't work for me.

**Comment by nitrada** [comment]
Can you check this @lukasondrej?

**Comment by lukasondrej** [comment]
Populating image placeholders with URLs should work as expected now. It'd be great if you could give it a go using the latest commit and let us know if it works for you.

**Comment by joshhillier** [comment]
I have just tested this with two different types of data, it seems to be working perfectly!
