### ISSUE TITLE
Can't use Symbol Overrides as placeholders

### ISSUE THREAD

**Issue by acleave** [preciousforever/sketch-data-populator#63]
When trying to create re-usable symbols, the nested text layers values don't match the JSON fields. I'd assume you could place the placeholder variable name (that matches the JSON) into the Symbol override, but that doesn't seem to work. It actually replaces the override with the string value of the text layer, which overwrites the placeholder.

I've attached an example. Thanks.

[Archive.zip](https://github.com/preciousforever/sketch-data-populator/files/338347/Archive.zip)

**Comment by nitrada** [comment]
@acleave thanks for reporting! We'll release an update that will improve populating sysmbols sometime in January 2017.

**Comment by nitrada** [comment]
@acleave we reworked the nested symbols populating behavior in v2.0.2: https://github.com/preciousforever/sketch-data-populator/releases/tag/v2.0.2

please check it out and let us know if everything works for you!

**Comment by hlambert** [comment]
Im still having problems getting this to work. Downloaded the zip-file from @acleave, and couldn't get that version working. Running Sketch 49.1.
