### ISSUE TITLE
Can't get data table to populate

### ISSUE THREAD

**Issue by citation-nm** [preciousforever/sketch-data-populator#64]
Hi there,

I'm having difficulty getting a 'data table' I've constructed in Sketch to populate with a corresponding JSON file, I have attached both for investigation.

Could someone have a look and see if what I'm trying to do is even possible?

Many thanks,

Neil
[company-contacts.zip](https://github.com/preciousforever/sketch-data-populator/files/346588/company-contacts.zip)

**Comment by e-thompson** [comment]
Im having the same issue

**Comment by citation-nm** [comment]
Good to know it's not just me :)

**Comment by e-thompson** [comment]
I did get this to work btw. I have found that you need to select the Artboard/Layers you want to populate. Also, the text inside the text box must be the proper {tag} and not just paragraph text, meaning this won't work on text boxes that already have text inside the text box. Good luck.

**Comment by citation-nm** [comment]
Thanks for the update - one thing I think I need to check is whether it plays nicely with text layers that have a size specified. I'll report back once I've done some further investigations.

**Comment by e-thompson** [comment]
Didn't wanna leave you hanging here, but Craft from Invision does all this with ease. I was bummed I didn't find that out till WAY after I was done with my project.

**Comment by iamaaronmartin** [comment]
To the credit of this plug-in, Craft doesn't let you define whole sets of data that travel together. And it's always random.
