### ISSUE TITLE
Numbers in json not working

### ISSUE THREAD

**Issue by BernsteinA** [preciousforever/sketch-data-populator#65]
Unless I wrap them in quotation marks

**Comment by zhenximi** [comment]
I have the same issue, it the text is empty when it's a number in Json

**Comment by lukasondrej** [comment]
The issue should now be fixed. Let us know if it works for you.

**Comment by nitrada** [comment]
thanks @lukasondrej!

**Comment by zhenximi** [comment]
Thanks @lukasondrej , now it working great!
