### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by bomberstudios** [preciousforever/sketch-data-populator#67]
Hi there,

As you probably know, `setPatternImage:` has been deprecated for a while, and it will be removed in Sketch v40. Please update your Plugin to use `setImage:` instead or it won't work in the next release :)

**Comment by nitrada** [comment]
Thanks for pointing @bomberstudios!

**Comment by lukasondrej** [comment]
Thanks, I'll take a look at that.
