### ISSUE TITLE
Using nested objects in JSON

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [preciousforever/sketch-data-populator#69]
I tried to use a nested object like: 

```
[
 {
    name: "Test"
    nested : {
     image : "images/image.jpg"
  }
 }
]
```

Actually I think the data populator does not support nested objects. 
It would be great to add that feature in a future realse. Referencing could work like: {nestes.image}

Thank you for the great work !
Alex

**Comment by MDBas** [comment]
This would be a great addition!

**Comment by lukasondrej** [comment]
Nested objects are now fully supported. You can also nest any number of objects, e.g. `{top.nested.anotherNested.property}`. Please try it out and let us know if it works for you.

**Comment by ossanti** [comment]
this doesnt apply to arrays inside an object right? I tried to do the following

`
[
    {
        "presets": {
            "preset_value": "Today"
        }
            
    }
]
`

but had no luck

**Comment by metalhaze** [comment]
@csantiago132 You don't navigate arrays the same way you navigate Objects.

arrayName[0].presets.preset_value    --> should give you "Today"

This should work, no?

**Comment by sirpooya** [comment]
This solution worked but what if I want preset_value for all of the array objects?

I'm looking for a feature like this in Data Path : arrayName[0-12].presets.preset_value
