### ISSUE TITLE
Renaming Groups

### ISSUE THREAD

**Issue by Ninerian** [preciousforever/sketch-data-populator#70]
Hello, 

thanks for this great plugin and the work you've invested. It really helps to save a lot of time! 👍 

Is it possible to rename the group, which contains the placeholders? I tried it by giving the group an placeholder name {id}, but it wasn't renamed.

**Comment by nitrada** [comment]
@Ninerian no, it doesn't replace Layer or layer Group names – just the content of Text Layers or "Image Layers". You can use a {placeholder} in a Text Layer name as a proxy to replace the whole Text Layer with respective data (that's eg useful for IconFonts).
