### ISSUE TITLE
Issues with a comma separated list

### ISSUE THREAD

**Issue by marcelosomers** [preciousforever/sketch-data-populator#72]
I'm using the contacts/full-data preset data. I want to populate lastname, firstname (e.g., Doe, John) similar to the animated GIF example in the README. Unless I'm missing something, there seems to be a bug in that just including a comma + space breaks.

I've tried several options to accomplish this, none of which work:

* `{lastname,firstname|&, }` loses the comma (Doe John)
* `{lastname}, {firstname}` only populates a last name
* `{lastname,firstname|& , }` (a space between the `&` and `,`) works fine, but I don't want spaces on both sides of the comma

Am I missing something with this, or did I hit a bug? Thanks!

**Comment by nitrada** [comment]
@marcelosomers should be fixed with v2.0.2:
https://github.com/preciousforever/sketch-data-populator/releases/tag/v2.0.2

**Comment by docmars** [comment]
Hey there, sorry to re-open this, but this is happening to me in v2.1.3, where I've entered a very simple string:

{symbol}:{exchange}

Then using the JSON populator, the colon ( : ) is getting lost after running it. 😞
