### ISSUE TITLE
chaining conditional actions

### ISSUE THREAD

**Issue by nitrada** [preciousforever/sketch-data-populator#73]
eg: `#hide["{Type}"="Text"] && #hide["{Type}"="Other”]`

is this already possible? or should we allow it in the future?
(it was a question via email)

**Comment by rockitbaby** [comment]
`#hide["{Type}"=="Text" || "{Type}"="Other"]`

works. inside square brackets: after evaluation of template variables, its an expression of pure javascript..

**Comment by nitrada** [comment]
great, thanks!
