### ISSUE TITLE
Conditional Action: 'swap'

### ISSUE THREAD

**Issue by nitrada** [preciousforever/sketch-data-populator#74]
it would be great to have the following conditional action:

`swapSymbol`

'swapSymbol' should also work with nested symbol overrides (to swap symbol instances inside symbols based on data).

**Comment by shannon-murdoch-webjet** [comment]
Love it @nitrada - used it today to affect the symbol used by one of my repeating elements:
![swapsymbol](https://cloud.githubusercontent.com/assets/2764182/22716462/436e33fa-edea-11e6-8f5f-bad1da59899e.png)

**Comment by nitrada** [comment]
that's awesome, @shannon-murdoch-webjet! 

would be so cool if you could share that "flight data card" example including the JSON for it. great source for learning! ;-)

**Comment by shannon-murdoch-webjet** [comment]
Sure - I'll share with you directly for now as it's pre-production work. :-)
