### ISSUE TITLE
Sketch 42 : can't update with JSON

### ISSUE THREAD

**Issue by evandeininger** [preciousforever/sketch-data-populator#76]
Since updating to Sketch 42 it looks like Data Populator doesn't want to work any more:
- Tried to select a layer with the appropriate layer name (in my case: `{article2.title}`) but nothing happened.
- Tried to see if error messaging comes up when nothing is selected and nothing appears.
- Reveal Presets still brings up finder with no issue, but everything else has no pulse.

**Comment by nitrada** [comment]
hey @evandeininger, v2.0.1 should fix this: https://github.com/preciousforever/sketch-data-populator/releases

**Comment by evandeininger** [comment]
Totally fixed sorry about that! Thanks @nitrada!

**Comment by nitrada** [comment]
Thanks for reporting. We had it fixed earlier but i only pushed the release after you created the issue! :-)
