### ISSUE TITLE
Fit images in shapes (Feature request)

### ISSUE THREAD

**Issue by vladmoroz** [preciousforever/sketch-data-populator#77]
Would be great to have a checkbox to set image pattern fill type to Fit instead of Fill

**Comment by nitrada** [comment]
@vladmoroz as a conditional action, you mean? meaning you can change this setting driven by data?

**Comment by vladmoroz** [comment]
Just a simple setting like [this](https://www.dropbox.com/s/kasmbigjuj9xtnz/Screenshot%202017-01-31%2017.00.05.png?dl=0)

Alternatively, would be great if plugin would respect layer's pattern fill type and not overwrite it

**Comment by nitrada** [comment]
> respect layer's pattern fill type and not overwrite it

that's something we could do, right @lukasondrej? (i think when we implemented it back then there were no options for the fill)

**Comment by shannon-murdoch-webjet** [comment]
Maybe a layer name based approach would be better... ie {imgURL | fill} or {imgURL | fit}

**Comment by rezaarkan** [comment]
> Alternatively, would be great if plugin would respect layer's pattern fill type and not overwrite it

Pull request for temporary disable on #78, as suggested by @vladmoroz

**Comment by nitrada** [comment]
thanks @rezaarkan @vladmoroz @shannon-murdoch-webjet!

please check out v2.1.2
https://github.com/preciousforever/sketch-data-populator/releases
