### ISSUE TITLE
Data Populator Usage Examples Library

### ISSUE THREAD

**Issue by nitrada** [preciousforever/sketch-data-populator#80]
We're currently collecting a Library of usage examples of **Sketch Data Populator**. So if there's something you would like to share with the world, please let us know and we'll publish your JSON and Sketch Examples in this repository and if you like, also integrate it into the official demo file.

Feel free to post screenshots or links here just like @shannon-murdoch-webjet did in the comments of https://github.com/preciousforever/sketch-data-populator/issues/74, or [send us an email](mailto:info@datapopulator.com).

**Comment by Mikola35** [comment]
I try use this plugin with this sites:

https://www.mockaroo.com/
A free test data generator and API mocking tool - Mockaroo lets you create custom CSV, JSON, SQL, and Excel datasets to test and demo your software.

https://www.lists.design/
Lists is a gallery of real content ready to populate your mockups. Produce your best work by making informed decisions.
