### ISSUE TITLE
why filter don't work, for example,{name | upper}, {name | -l n}? 

### ISSUE THREAD

**Issue by ployer900** [preciousforever/sketch-data-populator#84]

**Comment by nitrada** [comment]
@ployer900 can you please describe your issue with more details and give us an a example file to investigate?

**Comment by lajlev** [comment]
I have the same problem
Template
http://u.laj.lv/IZTe+

JSON
http://u.laj.lv/CZCh+

Settings
http://u.laj.lv/1757R+

Output
![image](https://cloud.githubusercontent.com/assets/133836/24540156/3ed23334-15f2-11e7-8632-87a5c7103993.png)
+

**Comment by ColeTownsend** [comment]
Having a similar issue, where the filters don't work. Strings are automatically lowercasing for me

**Comment by asgeirhoem** [comment]
Same as the comments above.

**Comment by endswithak** [comment]
I'm having similar issues. It seems like no matter what filter you select, it will always use the Lowercase filter.

**Comment by endswithak** [comment]
The for loop within the `applyFilter` function in `src/library/filters/index.js` is what's causing the issue.

#### Current
```javascript
for (let i = 0; i < filters.length; i++) {
  if (filters[i].name == filter.command || filters[i].alias == filter.command) {
    applyFunction = filters[i].apply
  }
}
```

#### Possible fix
```javascript
for (let i = 0; i < filters.length; i++) {
  if (filters[i].name == filter.param.trim() || filters[i].alias == filter.param.trim()) {
    applyFunction = filters[i].apply
  }
}
```

The current for loop checks to see if `filter.command` matches any of the filter names. This isn't good because `filter.command` is always going to be an empty string due to the `parseFilter` function in `src/library/filters/index.js`.

**Comment by endswithak** [comment]
It looks like the issue has to do with the `parseFilter` function in `src/library/filters/index.js`.

#### Current
``` javascript
export function parseFilter(filterString) {

  //get command
  let command = null
  for (let i = 0; i < filters.length; i++) {
    if (filterString.startsWith(filters[i].name)) {
      command = filters[i].name
      break;
    }
    else if (filterString.startsWith(filters[i].alias)) {
      command = filters[i].alias
      break;
    }
  }

  //get param by removing the command from the string
  let param = filterString.substring(command.length)

  //create filter
  let filter = {
    command: command.trim()
  }

  //add param to filter
  if (param.length && param.trim().length) filter.param = param

  return filter
}
```

#### Possible fix

```javascript
export function parseFilter(filterString) {

  let fstring = filterString.trim();

  //get command
  let command = null
  for (let i = 0; i < filters.length; i++) {
    if (fstring.startsWith(filters[i].name)) {
      command = filters[i].name
      break;
    }
    else if (fstring.startsWith(filters[i].alias) && filters[i].alias.length) {
      command = filters[i].alias
      break;
    }
  }

  //get param by removing the command from the string
  let param = fstring.substring(command.length)

  //create filter
  let filter = {
    command: command.trim()
  }

  //add param to filter
  if (param.length && param.trim().length) filter.param = param

  return filter
}
```

This fix replaces all instances of `filterString` with a new variable `fstring` and adds `&& filters[i].alias.length` to the for loop `else if` conditional.

**Comment by lukasondrej** [comment]
Filters should now work as expected. There are a few things to keep in mind though:

- `-l n` can only be added to layer name, not within a placeholder written in a text layer
- filters must be nested using `()` not `{}`, e.g. `{(valOne | upper | max 4), valTwo | & • }`
- if the text layer name contains a placeholder, it will override any placeholders contained in the text layer
