### ISSUE TITLE
Bug: Cannot use true, must use "true"

### ISSUE THREAD

**Issue by ColeTownsend** [preciousforever/sketch-data-populator#85]
Unfortunately it appears that checking for `true` as in `"{selected}" === true` does not work and we must do a string comparison.

![image](https://cloud.githubusercontent.com/assets/987654/23376825/92b2e242-fcfb-11e6-969a-798579af491c.png)

**Comment by lukasondrej** [comment]
@ColeTownsend to avoid the need for string comparison, please don't use quotes around **boolean** placeholders, e.g. if `selected` is a boolean value then `{selected} == true` is valid. `"{selected}" == true` is not valid because it renders to `"true" == true` for example. Hope this helps.
