### ISSUE TITLE
Exclude layers from the process

### ISSUE THREAD

**Issue by timothyachumba** [preciousforever/sketch-data-populator#88]
Some of my nested symbols are being overwritten with an empty string, I just want to exclude a particular layer or automatically exclude layers without `{}` present.

**Comment by nitrada** [comment]
If layer names or text layer content do not have a `{placeholder}` in them, they are automatically excluded. It might be that your layers that get overwritten with an empty string had been populated before. Try the Clear command to see if that's the case. Hope that helps!

**Comment by timothyachumba** [comment]
@nitrada I tried to clear everything but no luck, the layer is still being overwritten with a blank character.

**Comment by nitrada** [comment]
@timothyachumba what is the layer called (in the layers list)?
