### ISSUE TITLE
Populate using data from url

### ISSUE THREAD

**Issue by rssilva** [preciousforever/sketch-data-populator#9]
Is possible to use JSON data from a API available on an URL?

**Comment by nitrada** [comment]
"Populate from URL"?

**Comment by adyz** [comment]
This would be the best feature, not only of this plugin, but for sketch too!!!
Awesome ideea guys, keep up the work with this plugin!

**Comment by lajlev** [comment]
:+1:

**Comment by clarklab** [comment]
huge +1 here, but fear images would throw a kink in the plan

**Comment by clarklab** [comment]
related: today I wrote a little thing for my Jekyll blog to output data from live posts, ala http://chowdown.io/recipes.json

**Comment by nitrada** [comment]
I read about people rather writing a helper app to get and play around with data from an API, but store it as local JSON and assets, ready for use for the plugin. 

Best of both worlds: real-time access to an API, but the performance from local files.

**Comment by taiarock** [comment]
+1!!!

**Comment by tdemooij** [comment]
[This sketch-json-parser](https://github.com/kvendrik/sketch-json-parser) got it working with image url's. Unfortunately only as a bitmap, not at as a background fill.

**Comment by nitrada** [comment]
@tdemooij is it fast enough (given hundreds of images)?

**Comment by tdemooij** [comment]
@nitrada I don't know about hundreds. But I did a quick test with the recipes json from @clarklab. Have a look at the [screencast](https://dl.dropboxusercontent.com/u/5119421/screen_json.mov).

Its pretty quick. There are only 11 images, but they're around 500kb each.

**Comment by lasseklein** [comment]
+1

**Comment by nitrada** [comment]
We decided to keep it a locally operating kick ass plugin for now ;-)

we'll rather investigate in tools to gather/model data from different sources more easily.

**Comment by tdemooij** [comment]
I found out that's really easy to make a local copy of a JSON with Automator. This speeds up my workflow and makes a nice addition to this plugin. It would be even better if it would make a local copy of all the images in the JSON. It shouldn't be too hard to write some applescript for this, but my coding skills are pretty limited.

This is how my Automator workflow looks like:
![screen shot 2015-08-05 at 11 01 10](https://cloud.githubusercontent.com/assets/1323077/9082009/56778a06-3b61-11e5-9735-d8b08b57b3c5.png)

**Comment by ItsJoeTurner** [comment]
+1 for "Populate from URL" command. I'm working w/ live data to create a daily graphic.
