### ISSUE TITLE
Joins not working for dot syntax / nested objects

### ISSUE THREAD

**Issue by ColeTownsend** [preciousforever/sketch-data-populator#92]
![image](https://cloud.githubusercontent.com/assets/987654/24760729/8270a71e-1ab7-11e7-9a56-2243e8bd55a6.png)

![image](https://cloud.githubusercontent.com/assets/987654/24760737/86d17c2a-1ab7-11e7-982c-dca98931611f.png)

```
"location": {
      "id": 5,
      "name": "87 Summer St",
      ...
},
"level": {
      "id": 3,
      "location_id": 5,
      "name": "Floor 20"
}
```

**Comment by endswithak** [comment]
This might have to do with filters not working in general. I listed a possible fix in an older issue: https://github.com/preciousforever/sketch-data-populator/issues/84

**Comment by lukasondrej** [comment]
@ColeTownsend joins with dot syntax work as expected. The source of this issue was actually that the space between the pipe and the filter name was not allowed, e.g. {one,two | & • } didn't work but {one,two |& • } did. Now both work. Sorry for the confusion.
