### ISSUE TITLE
Text override is gone after 'populate again' 

### ISSUE THREAD

**Issue by tdemooij** [preciousforever/sketch-data-populator#95]
This illustrates it best:

![text override](https://cloud.githubusercontent.com/assets/1323077/24966374/0b77f550-1fa7-11e7-8e7d-64a31107aab0.gif)

I have a 'tag' symbol, within a 'contact' symbol. When I override the content of the text-layer within the 'tag' symbol, this texts resets when i do 'populate again'. I would expect it to remember the override.

You can download the [sketch file](https://www.dropbox.com/s/ctv78weaowq59wu/text-override.sketch?dl=0) here.

Any thoughts?

**Comment by lukasondrej** [comment]
@tdemooij please try the latest commit. Overrides that are not overwritten or cleared are kept, meaning that the example mentioned above now works as expected.

**Comment by tdemooij** [comment]
Great, thx!
