### ISSUE TITLE
Bug: No longer works with symbol overrides in Sketch 44

### ISSUE THREAD

**Issue by seandellis** [preciousforever/sketch-data-populator#98]
I upgraded Sketch today and found that symbol overrides no longer work it in version 44. I've attached an example file and video for debugging purposes.

![screenshot 2017-05-18 18 08 22](https://cloud.githubusercontent.com/assets/1584916/26227037/6b6ff2e0-3bf5-11e7-93ba-731837279f67.png)

This plugin is a lifesaver and I'd love to see it up and running again. Thank you!

[bug-symbol-data populator-sketch 44.zip](https://github.com/preciousforever/sketch-data-populator/files/1012655/bug-symbol-data.populator-sketch.44.zip)

**Comment by asgeirhoem** [comment]
+1

**Comment by nitrada** [comment]
@lukasondrej will have a look once he's back from his vacation (this week).

**Comment by seandellis** [comment]
@nitrada Thanks for the update. 😄

**Comment by lukasondrej** [comment]
@seandellis overrides now work in 44.

**Comment by andyra** [comment]
@lukasondrej Symbol overrides still aren't working for me with:

- Sketch 44.1
- Data Populator 2.1.3
- macOS 10.12.5

In addition to using a JSON file I normally use, I tried the demo.sketch file included in this repo using the demo presets without any luck. Is there anything more specific I can contribute that might help?

**Comment by eaugustine** [comment]
Yes, still not working for me either.
Sketch 44.1
Data Populator 2.1.3
macOS 10.11.13

**Comment by williambout** [comment]
It's not working for me either (building from master).
I managed to make it work by removing the symbols inside my main symbol.

**Comment by lukasondrej** [comment]
We'll do more testing, thanks for the comments!

**Comment by richardquay** [comment]
Thanks for looking into this! Do you might have an ETA on this?

**Comment by eaugustine** [comment]
Here's an extra piece of information. It DOES work if you select a symbol with nested symbols which you have previously tried to have populated with the plugin, and choose to replace the symbol with itself, either through the contextual menu or through the inspector panel. The data gets added that way. But if you then use the shortcut to repopulate the data, it goes back to the placeholders.

**Comment by vladmoroz** [comment]
Doesn't work for me as well.
Sketch 44.1, Data Populator 2.3.1, macOS 10.12.5

@eaugustine Thanks for the workaround. It's really weird that when replaced, symbol has data from JSON, but subsequent repopulation resets symbol to placholder data

**Comment by wolfganglattermann** [comment]
i can confirm that it's not working on sketch 44.1, data populator 2.1.3, macOs 10.12.4

as I am very happy that data populator allows the use of conditional actions, i would like to try the plugin with the newest version of sketch. might you give an ETA on this fix?

**Comment by lukasondrej** [comment]
Really sorry for the inconvenience, the fix will be ready very soon (as part of the next release).

**Comment by nitrada** [comment]
it should work with this release: https://github.com/preciousforever/sketch-data-populator/releases/tag/v2.2.0

please let us know if you're still running into troubles!

**Comment by seandellis** [comment]
@nitrada @lukasondrej  Yep, the latest release now works on my example file. Thanks so much for fixing this!

**Comment by ossanti** [comment]
sorry for bringing bad news but not working for me, the content gets replaced by empty spaces
<img width="895" alt="screenshot 2017-09-06 17 26 42" src="https://user-images.githubusercontent.com/5726971/30137440-f19cf752-9328-11e7-81a0-dbb3a243d906.png">
<img width="906" alt="screenshot 2017-09-06 17 27 29" src="https://user-images.githubusercontent.com/5726971/30137439-f19b5820-9328-11e7-88f1-b28fb5ea1d8f.png">
<img width="899" alt="screenshot 2017-09-06 17 27 36" src="https://user-images.githubusercontent.com/5726971/30137438-f197712e-9328-11e7-8d75-a4c41bc71fc4.png">
<img width="118" alt="screenshot 2017-09-06 17 27 49" src="https://user-images.githubusercontent.com/5726971/30137437-f1970d10-9328-11e7-8615-36decbc2ae24.png">

**Comment by ossanti** [comment]
not working for me :/ I'm getting empty spaces
Sketch: 46.2
Mac OS: 10.12.6
plugin: 2.2.0

<img width="895" alt="screenshot 2017-09-06 17 26 42" src="https://user-images.githubusercontent.com/5726971/30137521-5a9153fc-9329-11e7-80d3-de540e92da82.png">
<img width="906" alt="screenshot 2017-09-06 17 27 29" src="https://user-images.githubusercontent.com/5726971/30137519-5a8f9b5c-9329-11e7-8e8d-16709a26fc65.png">
<img width="899" alt="screenshot 2017-09-06 17 27 36" src="https://user-images.githubusercontent.com/5726971/30137522-5a92bd14-9329-11e7-8256-3400150b03c2.png">
<img width="118" alt="screenshot 2017-09-06 17 27 49" src="https://user-images.githubusercontent.com/5726971/30137520-5a8fc5aa-9329-11e7-8e1a-14d4da19463e.png">
